# На какой группе серверов
- hosts: staging

  vars:
    root_dir: /etc/nginx
    nginx_port: 8081

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes
      
    - name: update nginx config
      ansible.builtin.template: # имя модуля Ansible
        src: files/nginx.conf.j2
        dest: "{{root_dir}}/nginx.conf"
      tags: nginx
      
      notify:
        - restart nginx
      become: yes
     
    - name: create index.html file in nginx
      ansible.builtin.copy: # имя модуля Ansible
        src: files/index.html
        dest: /usr/share/nginx/html/index.html 
      
      notify:
        - restart nginx
      become: yes
 

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
        


